// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iddylnazxhwcukevwrst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlkZHlsbmF6eGh3Y3VrZXZ3cnN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MDY1MjQsImV4cCI6MjA3NDI4MjUyNH0.nUYjy9W6kw9GFzym_oI-Wz6KXkbvNDI7WC75Wv6-FdE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});